language: node_js

node_js:
  - "iojs"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" = "0.6" ] || npm install -g npm@1.4.28 && npm install -g npm'

sudo: false
